name: Deploy to itch.io

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Export Godot Project (Web)
      uses: firebelley/godot-export@v6.0.0  # Updated to latest version :cite[1]:cite[2]
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.4/Godot_v4.4-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.4/Godot_v4.4-stable_export_templates.tpz
        relative_project_path: ./
        use_preset_export_path: true  # Use path from export_presets.cfg :cite[1]
        cache: true  # Faster subsequent builds :cite[3]

    - name: Install Butler
      run: |
        curl -s -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip -q butler.zip
        chmod +x butler
        ./butler -V

    - name: Deploy to itch.io
      run: |
        ./butler push --fix-permissions --verbose ./web ${{ secrets.ITCH_USERNAME }}/${{ secrets.ITCH_GAME_NAME }}:web
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
